### ISSUE TITLE
Colorblind Options/Support

### ISSUE THREAD

**Issue by FlashSkyNews** [SKUDONET/skdlb#3]
Hey

as a color blind person with a deuteran deficiency I would really appriciate a change of the red and green colors or maybe even some icons in SKUDONET Community and Enterprise. It isn't critical change, but one which would save me time trying to find a green dot for example.

![image](https://github.com/SKUDONET/skdlb/assets/24974529/287b1b23-5dc9-491d-bcd1-c226814d6e99)

**Comment by emiliocamposmartin** [comment]
You are right, we will manage this as different icons. 

Thanks!

**Comment by dev-team-skudonet** [comment]
Good day, this feature has been added to the product, please check the latest community support, Status icons are more descriptive now, we have stopped using a ball for the status identification.

Thanks for your comments!
