### ISSUE TITLE
Windows authentication in load balance

### ISSUE THREAD

**Issue by AMFSysAdmin** [SKUDONET/skdlb#5]
Hi, i have 2 iis servers with several apps .... the app have windows autenthication enabled....if i acces via htp://serveriis1/app autenticate correctly but if i access via load balancer always prompt me a pop up ask me user and password. 

Someone can help me?

regards!

**Comment by emiliocamposmartin** [comment]
It sounds like and issue with NTLM or persistence, in case you configure more than one backend then persistence is totally required. Please enable a persistence session based in IP and confirm it works for you. 

Regards

**Comment by AMFSysAdmin** [comment]
i tried to set my farm in http profile and in L4xnat profile....both persistente sesion based in IP and didn't work for me.

![image](https://github.com/SKUDONET/skdlb/assets/101095106/de21b901-e671-446b-bd2c-f6b00721d713)


![image](https://github.com/SKUDONET/skdlb/assets/101095106/283d0a73-0127-4240-bf01-5fc95ff5a1c4)


Any idea?

**Comment by emiliocamposmartin** [comment]
Hi the global section that you shared with us seems to be configured properly for a virtual IP using the TCP port 80 and listening on HTTP mode, but to help you, please give us more information. 

What configuration did you do in the service section? What kind of error do you see? Are the clients able to connect to the Virtual IP and virtual Port? Are the load balancer able to connect against the backend servers? Are your clients connecting to the backend and passing through the load balancer but they lose the session? If so did you configure the persistence session based on IP? 

As much information you share with us as much better to figure out what is going on.

**Comment by emiliocamposmartin** [comment]
I realized you configured the URL pattern /iGastos, the system is case-sensitive, so if the URL is not exactly as indicated it is not going to work. you can use this flag to disable case sensitive (?i) in the URL field. /(?i)iGastos/

**Comment by emiliocamposmartin** [comment]
Did you have the chance of checking my latest proposal? Any update will be welcomed.

On the other hand please refer to this article to know more about Service configuration, as it seems to be related with some configuration issue. 

Update HTTP(S) fields:
https://www.skudonet.com/knowledge-base/community-edition-v7-0-administration-guide/lslb-farms-update-http-profile/
And how to configure Virtual Host and URL to let HTTP profile takes load balancing decisions: 
https://www.skudonet.com/knowledge-base/howtos/load-balancing-high-availability-application-servers-tomcat-jboss-iis/

**Comment by dev-team-skudonet** [comment]
HI @AMFSysAdmin, thanks for sharing with me information in private, after doing some tests we realized that the browser was sending Kerberos tokens to the load balancer in case the consumed service is a DNS Host already configured in Active Directory.

This issue is not related to the load balancer itself but to the client side. 

Thanks for the confirmation.

Regards!
