### ISSUE TITLE
Spelling mistake in log files

### ISSUE THREAD

**Issue by drsbaitso** [SKUDONET/skdlb#7]
In the skdinotify.log file the initial sync has a mispelling of first.

It says : Running the firs replication...

Should say : Running the firs**t** replication...

**Comment by emiliocamposmartin** [comment]
Fixed in git, it will be fixed in the following release. 

Thanks!

**Comment by dev-team-skudonet** [comment]
We will proceed to close this issue as the code has been modified in our lab, skudonet-ce-cluster is the deb package that need to be updated. 

We are preparing a new SKUDONET version, we will try to release it in the following weeks. 

Regards!
